app = "portofoliojalil" 

[build]
  image = "mcr.microsoft.com/dotnet/aspnet:8.0"

[env]
  ASPNETCORE_URLS = "http://+:8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
